### ISSUE TITLE
Problem with huge numeric strings

### ISSUE THREAD

**Issue by shaagerup** [ochrons/boopickle#49] opened 2016-02-12 10:48 UTC
A string with value "13065136436328809018" currently gets decoded as "-5381607637380742598". It seems that this is due to boopickle's optimizations for numeric strings - I believe the bounds on line [Pickler.scala#L154](https://github.com/ochrons/boopickle/blob/53a7437b13dc2423a2f1c12e817fec41cbb06106/boopickle/shared/src/main/scala/boopickle/Pickler.scala#L154) are too wide.

**Comment by ochrons** [comment] 2016-02-12 14:53
This is a duplicate of #48

**Closed by ochrons** 2016-02-12 14:53 UTC
Labels: duplicate
